In [85]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split 
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
from sklearn.neighbors import KNeighborsClassifier
import sys
import copy

In [86]:
testing = pd.DataFrame()

In [87]:
def robot1(testing):
    df=pd.read_table("RobotDataset/Robot1",delim_whitespace=True,names=('class','a1','a2','a3','a4','a5','a6','Id'))
    k = 5

    X = df.drop(['class','Id'],axis=1)
    Y = df['class']
    X_train, X_test, Y_train, Y_test = train_test_split(X,Y,test_size = 0.2)

    def cosine_similarity(x, y):
        return np.dot(x, y) / (np.sqrt(np.dot(x, x)) * np.sqrt(np.dot(y, y)))

    Y_train = list(Y_train)
    pred = []
    for index,row in X_test.iterrows():
        dist= []
        for index1,row1 in X_train.iterrows():
            dist.append(1-cosine_similarity(row,row1))

        our = pd.DataFrame(
        {'a': dist,
         'b': Y_train
        })
        our = our.sort_values(by=['a'])
        counts_zero = 0
        counts_one = 0
        i = 0
        for index,row in our.iterrows():
            if i >= k:
                break
            if int(row['b']) == 0:
                counts_zero = counts_zero + 1 
            elif int(row['b']) == 1:
                counts_one = counts_one + 1 
            i = i + 1
        if counts_zero > counts_one:
            pred.append(0)
        else:
            pred.append(1)


    print(confusion_matrix(Y_test,pred))
    print(classification_report(Y_test,pred))
    print(accuracy_score(Y_test, pred)*100)

    neigh = KNeighborsClassifier()
    neigh.fit(X_train, Y_train) 
    y_pred = neigh.predict(X_test)
    print(confusion_matrix(Y_test,y_pred))
    print(classification_report(Y_test,y_pred))
    print(accuracy_score(Y_test, y_pred)*100)
    
    if testing.empty:
        pass
    else:
        pred = []
        for index,row in testing.iterrows():
            dist= []
            for index1,row1 in X_train.iterrows():
                dist.append(1-cosine_similarity(row,row1))

            our = pd.DataFrame(
            {'a': dist,
             'b': Y_train
            })
            our = our.sort_values(by=['a'])
            counts_zero = 0
            counts_one = 0
            i = 0
            for index,row in our.iterrows():
                if i >= k:
                    break
                if int(row['b']) == 0:
                    counts_zero = counts_zero + 1 
                elif int(row['b']) == 1:
                    counts_one = counts_one + 1 
                i = i + 1
            if counts_zero > counts_one:
                pred.append(0)
            else:
                pred.append(1)
        print(pred)

In [88]:
def robot2(testing):
    df=pd.read_table("RobotDataset/Robot2",delim_whitespace=True)
    k = 5

    X = df.drop(['A','H'],axis=1)
    Y = df['A']
    X_train, X_test, Y_train, Y_test = train_test_split(X,Y,test_size = 0.2)

    def cosine_similarity(x, y):
        return np.dot(x, y) / (np.sqrt(np.dot(x, x)) * np.sqrt(np.dot(y, y)))

    Y_train = list(Y_train)
    pred = []
    for index,row in X_test.iterrows():
        dist= []
        for index1,row1 in X_train.iterrows():
            dist.append(1-cosine_similarity(row,row1))

        our = pd.DataFrame(
        {'a': dist,
         'b': Y_train
        })
        our = our.sort_values(by=['a'])
        counts_zero = 0
        counts_one = 0
        i = 0
        for index,row in our.iterrows():
            if i >= k:
                break
            if int(row['b']) == 0:
                counts_zero = counts_zero + 1 
            elif int(row['b']) == 1:
                counts_one = counts_one + 1 
            i = i + 1
        if counts_zero > counts_one:
            pred.append(0)
        else:
            pred.append(1)
            
    print(confusion_matrix(Y_test,pred))
    print(classification_report(Y_test,pred))
    print(accuracy_score(Y_test, pred)*100)

    neigh = KNeighborsClassifier()
    neigh.fit(X_train, Y_train) 
    y_pred = neigh.predict(X_test)
    print(confusion_matrix(Y_test,y_pred))
    print(classification_report(Y_test,y_pred))
    print(accuracy_score(Y_test, y_pred)*100)
    
    if testing.empty:
        pass
    else:
        pred = []
        for index,row in testing.iterrows():
            dist= []
            for index1,row1 in X_train.iterrows():
                dist.append(1-cosine_similarity(row,row1))

            our = pd.DataFrame(
            {'a': dist,
             'b': Y_train
            })
            our = our.sort_values(by=['a'])
            counts_zero = 0
            counts_one = 0
            i = 0
            for index,row in our.iterrows():
                if i >= k:
                    break
                if int(row['b']) == 0:
                    counts_zero = counts_zero + 1 
                elif int(row['b']) == 1:
                    counts_one = counts_one + 1 
                i = i + 1
            if counts_zero > counts_one:
                pred.append(0)
            else:
                pred.append(1)
        print(pred)


In [89]:
testing = pd.DataFrame()
try:
    testfilename = sys.argv[1]
    testing = pd.read_table(testfilename,delim_whitespace=True,names=('a1','a2','a3','a4','a5','a6','Id'))
    testing = testing.drop(['Id'],axis=1)
    robot1(testing)
except:
    testing=testing.iloc[0:0]
    robot1(testing)

/home/vatsal/.local/lib/python3.6/site-packages/ipykernel_launcher.py:4: FutureWarning: read_table is deprecated, use read_csv instead, passing sep='\t'.
  after removing the cwd from sys.path.
/home/vatsal/.local/lib/python3.6/site-packages/ipykernel_launcher.py:2: FutureWarning: read_table is deprecated, use read_csv instead, passing sep='\t'.
  


[[13  2]
 [ 1  9]]
              precision    recall  f1-score   support

           0       0.93      0.87      0.90        15
           1       0.82      0.90      0.86        10

   micro avg       0.88      0.88      0.88        25
   macro avg       0.87      0.88      0.88        25
weighted avg       0.88      0.88      0.88        25

88.0
[[14  1]
 [ 1  9]]
              precision    recall  f1-score   support

           0       0.93      0.93      0.93        15
           1       0.90      0.90      0.90        10

   micro avg       0.92      0.92      0.92        25
   macro avg       0.92      0.92      0.92        25
weighted avg       0.92      0.92      0.92        25

92.0


In [90]:
testing = pd.DataFrame()
try:
    testfilename = sys.argv[2]
    testing = pd.read_table(testfilename,delim_whitespace=True)
    testing = testing.drop(['H'],axis=1)
    robot2(testing)
except:
    testing=testing.iloc[0:0]
    robot2(testing)

/home/vatsal/.local/lib/python3.6/site-packages/ipykernel_launcher.py:4: FutureWarning: read_table is deprecated, use read_csv instead, passing sep='\t'.
  after removing the cwd from sys.path.
/home/vatsal/.local/lib/python3.6/site-packages/ipykernel_launcher.py:2: FutureWarning: read_table is deprecated, use read_csv instead, passing sep='\t'.
  


[[11  0]
 [ 5  9]]
              precision    recall  f1-score   support

           0       0.69      1.00      0.81        11
           1       1.00      0.64      0.78        14

   micro avg       0.80      0.80      0.80        25
   macro avg       0.84      0.82      0.80        25
weighted avg       0.86      0.80      0.80        25

80.0
[[ 9  2]
 [ 1 13]]
              precision    recall  f1-score   support

           0       0.90      0.82      0.86        11
           1       0.87      0.93      0.90        14

   micro avg       0.88      0.88      0.88        25
   macro avg       0.88      0.87      0.88        25
weighted avg       0.88      0.88      0.88        25

88.0


In [91]:
df=pd.read_csv("Iris/Iris.csv",names=['sepal length','sepal width','petal length','petal width','class'])
k = 5

In [92]:
X = df.drop(['class'],axis=1)
Y = df['class']
X_train, X_test, Y_train, Y_test = train_test_split(X,Y,test_size = 0.2)

In [93]:
testing = pd.DataFrame()
try:
    testfilename = sys.argv[3]
    testing = pd.read_csv(testfilename,names=['sepal length','sepal width','petal length','petal width'])
except:
    testing=testing.iloc[0:0]

In [94]:
def euclidean_distance(x, y):   
    ans = np.sqrt(np.sum((x - y) ** 2))
    return ans

In [95]:
Y_train = list(Y_train)
pred = []
for index,row in X_test.iterrows():
    dist= []
    for index1,row1 in X_train.iterrows():
        dist.append(euclidean_distance(row,row1))
        
    our = pd.DataFrame(
    {'a': dist,
     'b': Y_train
    })
    our = our.sort_values(by=['a'])
    sentosa = 0
    virginica = 0
    versicolor = 0
    i = 0
    for index,row in our.iterrows():
        if i >= k:
            break
        if row['b'] == "Iris-setosa":
            sentosa = sentosa + 1 
        elif row['b'] == "Iris-virginica":
            virginica = virginica + 1 
        elif row['b'] == "Iris-versicolor":
            versicolor = versicolor + 1 
        i = i + 1
    if sentosa >= virginica and sentosa >= versicolor:
        pred.append("Iris-setosa")
    elif virginica >= sentosa and virginica >= versicolor:
        pred.append("Iris-virginica")
    elif versicolor >= sentosa and versicolor >= virginica:
        pred.append("Iris-versicolor")
# print(pred)

In [96]:
print(confusion_matrix(Y_test,pred))
print(classification_report(Y_test,pred))
print(accuracy_score(Y_test, pred)*100)

[[11  0  0]
 [ 0  7  0]
 [ 0  0  9]]
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        11
Iris-versicolor       1.00      1.00      1.00         7
 Iris-virginica       1.00      1.00      1.00         9

      micro avg       1.00      1.00      1.00        27
      macro avg       1.00      1.00      1.00        27
   weighted avg       1.00      1.00      1.00        27

100.0


In [97]:
neigh = KNeighborsClassifier()
neigh.fit(X_train, Y_train) 
y_pred = neigh.predict(X_test)
print(confusion_matrix(Y_test,y_pred))
print(classification_report(Y_test,y_pred))
print(accuracy_score(Y_test, y_pred)*100)

[[11  0  0]
 [ 0  7  0]
 [ 0  0  9]]
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        11
Iris-versicolor       1.00      1.00      1.00         7
 Iris-virginica       1.00      1.00      1.00         9

      micro avg       1.00      1.00      1.00        27
      macro avg       1.00      1.00      1.00        27
   weighted avg       1.00      1.00      1.00        27

100.0


In [98]:
if testing.empty:
    pass
else:
    Y_train = list(Y_train)
    pred = []
    for index,row in testing.iterrows():
        dist= []
        for index1,row1 in X_train.iterrows():
            dist.append(euclidean_distance(row,row1))

        our = pd.DataFrame(
        {'a': dist,
         'b': Y_train
        })
        our = our.sort_values(by=['a'])
        sentosa = 0
        virginica = 0
        versicolor = 0
        i = 0
        for index,row in our.iterrows():
            if i >= k:
                break
            if row['b'] == "Iris-setosa":
                sentosa = sentosa + 1 
            elif row['b'] == "Iris-virginica":
                virginica = virginica + 1 
            elif row['b'] == "Iris-versicolor":
                versicolor = versicolor + 1 
            i = i + 1
        if sentosa >= virginica and sentosa >= versicolor:
            pred.append("Iris-setosa")
        elif virginica >= sentosa and virginica >= versicolor:
            pred.append("Iris-virginica")
        elif versicolor >= sentosa and versicolor >= virginica:
            pred.append("Iris-versicolor")
    print(pred)