In [8]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split 
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
from sklearn.neighbors import KNeighborsClassifier
import copy

In [9]:
def robot1():
    df=pd.read_table("RobotDataset/Robot1",delim_whitespace=True,names=('class','a1','a2','a3','a4','a5','a6','Id'))
    k = 5

    X = df.drop(['class','Id'],axis=1)
    Y = df['class']
    X_train, X_test, Y_train, Y_test = train_test_split(X,Y,test_size = 0.2)

    def cosine_similarity(x, y):
        return np.dot(x, y) / (np.sqrt(np.dot(x, x)) * np.sqrt(np.dot(y, y)))

    Y_train = list(Y_train)
    pred = []
    for index,row in X_test.iterrows():
        dist= []
        for index1,row1 in X_train.iterrows():
            dist.append(1-cosine_similarity(row,row1))

        our = pd.DataFrame(
        {'a': dist,
         'b': Y_train
        })
        our = our.sort_values(by=['a'])
        counts_zero = 0
        counts_one = 0
        i = 0
        for index,row in our.iterrows():
            if i >= k:
                break
            if int(row['b']) == 0:
                counts_zero = counts_zero + 1 
            elif int(row['b']) == 1:
                counts_one = counts_one + 1 
            i = i + 1
        if counts_zero > counts_one:
            pred.append(0)
        else:
            pred.append(1)


    print(confusion_matrix(Y_test,pred))
    print(classification_report(Y_test,pred))
    print(accuracy_score(Y_test, pred)*100)

    neigh = KNeighborsClassifier()
    neigh.fit(X_train, Y_train) 
    y_pred = neigh.predict(X_test)
    print(confusion_matrix(Y_test,y_pred))
    print(classification_report(Y_test,y_pred))
    print(accuracy_score(Y_test, y_pred)*100)

In [10]:
def robot2():
    df=pd.read_table("RobotDataset/Robot2",delim_whitespace=True)
    k = 5

    X = df.drop(['A','H'],axis=1)
    Y = df['A']
    X_train, X_test, Y_train, Y_test = train_test_split(X,Y,test_size = 0.2)

    def cosine_similarity(x, y):
        return np.dot(x, y) / (np.sqrt(np.dot(x, x)) * np.sqrt(np.dot(y, y)))

    Y_train = list(Y_train)
    pred = []
    for index,row in X_test.iterrows():
        dist= []
        for index1,row1 in X_train.iterrows():
            dist.append(1-cosine_similarity(row,row1))

        our = pd.DataFrame(
        {'a': dist,
         'b': Y_train
        })
        our = our.sort_values(by=['a'])
        counts_zero = 0
        counts_one = 0
        i = 0
        for index,row in our.iterrows():
            if i >= k:
                break
            if int(row['b']) == 0:
                counts_zero = counts_zero + 1 
            elif int(row['b']) == 1:
                counts_one = counts_one + 1 
            i = i + 1
        if counts_zero > counts_one:
            pred.append(0)
        else:
            pred.append(1)


    print(confusion_matrix(Y_test,pred))
    print(classification_report(Y_test,pred))
    print(accuracy_score(Y_test, pred)*100)

    neigh = KNeighborsClassifier()
    neigh.fit(X_train, Y_train) 
    y_pred = neigh.predict(X_test)
    print(confusion_matrix(Y_test,y_pred))
    print(classification_report(Y_test,y_pred))
    print(accuracy_score(Y_test, y_pred)*100)

In [11]:
robot1()

/home/vatsal/.local/lib/python3.6/site-packages/ipykernel_launcher.py:2: FutureWarning: read_table is deprecated, use read_csv instead, passing sep='\t'.
  


[[13  0]
 [ 2 10]]
              precision    recall  f1-score   support

           0       0.87      1.00      0.93        13
           1       1.00      0.83      0.91        12

   micro avg       0.92      0.92      0.92        25
   macro avg       0.93      0.92      0.92        25
weighted avg       0.93      0.92      0.92        25

92.0
[[13  0]
 [ 3  9]]
              precision    recall  f1-score   support

           0       0.81      1.00      0.90        13
           1       1.00      0.75      0.86        12

   micro avg       0.88      0.88      0.88        25
   macro avg       0.91      0.88      0.88        25
weighted avg       0.90      0.88      0.88        25

88.0


In [12]:
robot2()

/home/vatsal/.local/lib/python3.6/site-packages/ipykernel_launcher.py:2: FutureWarning: read_table is deprecated, use read_csv instead, passing sep='\t'.
  


[[11  1]
 [ 5  8]]
              precision    recall  f1-score   support

           0       0.69      0.92      0.79        12
           1       0.89      0.62      0.73        13

   micro avg       0.76      0.76      0.76        25
   macro avg       0.79      0.77      0.76        25
weighted avg       0.79      0.76      0.76        25

76.0
[[11  1]
 [ 4  9]]
              precision    recall  f1-score   support

           0       0.73      0.92      0.81        12
           1       0.90      0.69      0.78        13

   micro avg       0.80      0.80      0.80        25
   macro avg       0.82      0.80      0.80        25
weighted avg       0.82      0.80      0.80        25

80.0
