In [283]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split 
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
from sklearn.neighbors import KNeighborsClassifier
import copy

In [284]:
def robot1():
    df=pd.read_table("RobotDataset/Robot1",delim_whitespace=True,names=('A','B','C','D','E','F','G','H'))
    k = 5

    X = df.drop(['A','H'],axis=1)
    Y = df['A']
    X_train, X_test, Y_train, Y_test = train_test_split(X,Y,test_size = 0.2)

    def cosine_similarity(x, y):
        return np.dot(x, y) / (np.sqrt(np.dot(x, x)) * np.sqrt(np.dot(y, y)))

    Y_train = list(Y_train)
    pred = []
    for index,row in X_test.iterrows():
        dist= []
        for index1,row1 in X_train.iterrows():
            dist.append(1-cosine_similarity(row,row1))

        our = pd.DataFrame(
        {'a': dist,
         'b': Y_train
        })
        our = our.sort_values(by=['a'])
        counts_zero = 0
        counts_one = 0
        i = 0
        for index,row in our.iterrows():
            if i >= k:
                break
            if int(row['b']) == 0:
                counts_zero = counts_zero + 1 
            elif int(row['b']) == 1:
                counts_one = counts_one + 1 
            i = i + 1
        if counts_zero > counts_one:
            pred.append(0)
        else:
            pred.append(1)


    print confusion_matrix(Y_test,pred)
    print classification_report(Y_test,pred)
    print accuracy_score(Y_test, pred)*100

    neigh = KNeighborsClassifier()
    neigh.fit(X_train, Y_train) 
    y_pred = neigh.predict(X_test)
    print confusion_matrix(Y_test,y_pred)
    print classification_report(Y_test,y_pred)
    print accuracy_score(Y_test, y_pred)*100

In [285]:
def robot2():
    df=pd.read_table("RobotDataset/Robot2",delim_whitespace=True)
    k = 5

    X = df.drop(['A','H'],axis=1)
    Y = df['A']
    X_train, X_test, Y_train, Y_test = train_test_split(X,Y,test_size = 0.2)

    def cosine_similarity(x, y):
        return np.dot(x, y) / (np.sqrt(np.dot(x, x)) * np.sqrt(np.dot(y, y)))

    Y_train = list(Y_train)
    pred = []
    for index,row in X_test.iterrows():
        dist= []
        for index1,row1 in X_train.iterrows():
            dist.append(1-cosine_similarity(row,row1))

        our = pd.DataFrame(
        {'a': dist,
         'b': Y_train
        })
        our = our.sort_values(by=['a'])
        counts_zero = 0
        counts_one = 0
        i = 0
        for index,row in our.iterrows():
            if i >= k:
                break
            if int(row['b']) == 0:
                counts_zero = counts_zero + 1 
            elif int(row['b']) == 1:
                counts_one = counts_one + 1 
            i = i + 1
        if counts_zero > counts_one:
            pred.append(0)
        else:
            pred.append(1)


    print confusion_matrix(Y_test,pred)
    print classification_report(Y_test,pred)
    print accuracy_score(Y_test, pred)*100

    neigh = KNeighborsClassifier()
    neigh.fit(X_train, Y_train) 
    y_pred = neigh.predict(X_test)
    print confusion_matrix(Y_test,y_pred)
    print classification_report(Y_test,y_pred)
    print accuracy_score(Y_test, y_pred)*100

In [286]:
robot1()

[[ 9  1]
 [ 3 12]]
              precision    recall  f1-score   support

           0       0.75      0.90      0.82        10
           1       0.92      0.80      0.86        15

   micro avg       0.84      0.84      0.84        25
   macro avg       0.84      0.85      0.84        25
weighted avg       0.85      0.84      0.84        25

84.0
[[10  0]
 [ 3 12]]
              precision    recall  f1-score   support

           0       0.77      1.00      0.87        10
           1       1.00      0.80      0.89        15

   micro avg       0.88      0.88      0.88        25
   macro avg       0.88      0.90      0.88        25
weighted avg       0.91      0.88      0.88        25

88.0


In [287]:
robot2()

[[12  3]
 [ 2  8]]
              precision    recall  f1-score   support

           0       0.86      0.80      0.83        15
           1       0.73      0.80      0.76        10

   micro avg       0.80      0.80      0.80        25
   macro avg       0.79      0.80      0.79        25
weighted avg       0.81      0.80      0.80        25

80.0
[[12  3]
 [ 1  9]]
              precision    recall  f1-score   support

           0       0.92      0.80      0.86        15
           1       0.75      0.90      0.82        10

   micro avg       0.84      0.84      0.84        25
   macro avg       0.84      0.85      0.84        25
weighted avg       0.85      0.84      0.84        25

84.0
