In [11]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split 
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
from sklearn.neighbors import KNeighborsClassifier
import copy

In [12]:
df=pd.read_csv("Iris/Iris.csv",names=['A','B','C','D','E'])
k = 5

In [13]:
X = df.drop(['E'],axis=1)
Y = df['E']
X_train, X_test, Y_train, Y_test = train_test_split(X,Y,test_size = 0.2)

In [14]:
def euclidean_distance(x, y):   
    ans = np.sqrt(np.sum((x - y) ** 2))
    return ans

In [15]:
Y_train = list(Y_train)
pred = []
for index,row in X_test.iterrows():
    dist= []
    for index1,row1 in X_train.iterrows():
        dist.append(euclidean_distance(row,row1))
        
    our = pd.DataFrame(
    {'a': dist,
     'b': Y_train
    })
    our = our.sort_values(by=['a'])
    sentosa = 0
    virginica = 0
    versicolor = 0
    i = 0
    for index,row in our.iterrows():
        if i >= k:
            break
        if row['b'] == "Iris-setosa":
            sentosa = sentosa + 1 
        elif row['b'] == "Iris-virginica":
            virginica = virginica + 1 
        elif row['b'] == "Iris-versicolor":
            versicolor = versicolor + 1 
        i = i + 1
    if sentosa >= virginica and sentosa >= versicolor:
        pred.append("Iris-setosa")
    elif virginica >= sentosa and virginica >= versicolor:
        pred.append("Iris-virginica")
    elif versicolor >= sentosa and versicolor >= virginica:
        pred.append("Iris-versicolor")


In [16]:
print confusion_matrix(Y_test,pred)
print classification_report(Y_test,pred)
print accuracy_score(Y_test, pred)*100

[[11  0  0]
 [ 0  6  0]
 [ 0  0 10]]
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        11
Iris-versicolor       1.00      1.00      1.00         6
 Iris-virginica       1.00      1.00      1.00        10

      micro avg       1.00      1.00      1.00        27
      macro avg       1.00      1.00      1.00        27
   weighted avg       1.00      1.00      1.00        27

100.0


In [17]:
neigh = KNeighborsClassifier()
neigh.fit(X_train, Y_train) 
y_pred = neigh.predict(X_test)
print confusion_matrix(Y_test,y_pred)
print classification_report(Y_test,y_pred)
print accuracy_score(Y_test, y_pred)*100

[[11  0  0]
 [ 0  6  0]
 [ 0  0 10]]
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        11
Iris-versicolor       1.00      1.00      1.00         6
 Iris-virginica       1.00      1.00      1.00        10

      micro avg       1.00      1.00      1.00        27
      macro avg       1.00      1.00      1.00        27
   weighted avg       1.00      1.00      1.00        27

100.0
