In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split 
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
from sklearn.neighbors import KNeighborsClassifier
import copy

In [2]:
def robot1():
    df=pd.read_table("RobotDataset/Robot1",delim_whitespace=True,names=('class','a1','a2','a3','a4','a5','a6','Id'))
    k = 5

    X = df.drop(['class','Id'],axis=1)
    Y = df['class']
    X_train, X_test, Y_train, Y_test = train_test_split(X,Y,test_size = 0.2)

    def cosine_similarity(x, y):
        return np.dot(x, y) / (np.sqrt(np.dot(x, x)) * np.sqrt(np.dot(y, y)))

    Y_train = list(Y_train)
    pred = []
    for index,row in X_test.iterrows():
        dist= []
        for index1,row1 in X_train.iterrows():
            dist.append(1-cosine_similarity(row,row1))

        our = pd.DataFrame(
        {'a': dist,
         'b': Y_train
        })
        our = our.sort_values(by=['a'])
        counts_zero = 0
        counts_one = 0
        i = 0
        for index,row in our.iterrows():
            if i >= k:
                break
            if int(row['b']) == 0:
                counts_zero = counts_zero + 1 
            elif int(row['b']) == 1:
                counts_one = counts_one + 1 
            i = i + 1
        if counts_zero > counts_one:
            pred.append(0)
        else:
            pred.append(1)


    print(confusion_matrix(Y_test,pred))
    print(classification_report(Y_test,pred))
    print(accuracy_score(Y_test, pred)*100)

    neigh = KNeighborsClassifier()
    neigh.fit(X_train, Y_train) 
    y_pred = neigh.predict(X_test)
    print(confusion_matrix(Y_test,y_pred))
    print(classification_report(Y_test,y_pred))
    print(accuracy_score(Y_test, y_pred)*100)

In [3]:
def robot2():
    df=pd.read_table("RobotDataset/Robot2",delim_whitespace=True)
    k = 5

    X = df.drop(['A','H'],axis=1)
    Y = df['A']
    X_train, X_test, Y_train, Y_test = train_test_split(X,Y,test_size = 0.2)

    def cosine_similarity(x, y):
        return np.dot(x, y) / (np.sqrt(np.dot(x, x)) * np.sqrt(np.dot(y, y)))

    Y_train = list(Y_train)
    pred = []
    for index,row in X_test.iterrows():
        dist= []
        for index1,row1 in X_train.iterrows():
            dist.append(1-cosine_similarity(row,row1))

        our = pd.DataFrame(
        {'a': dist,
         'b': Y_train
        })
        our = our.sort_values(by=['a'])
        counts_zero = 0
        counts_one = 0
        i = 0
        for index,row in our.iterrows():
            if i >= k:
                break
            if int(row['b']) == 0:
                counts_zero = counts_zero + 1 
            elif int(row['b']) == 1:
                counts_one = counts_one + 1 
            i = i + 1
        if counts_zero > counts_one:
            pred.append(0)
        else:
            pred.append(1)


    print(confusion_matrix(Y_test,pred))
    print(classification_report(Y_test,pred))
    print(accuracy_score(Y_test, pred)*100)

    neigh = KNeighborsClassifier()
    neigh.fit(X_train, Y_train) 
    y_pred = neigh.predict(X_test)
    print(confusion_matrix(Y_test,y_pred))
    print(classification_report(Y_test,y_pred))
    print(accuracy_score(Y_test, y_pred)*100)

In [4]:
robot1()

/home/vatsal/.local/lib/python3.6/site-packages/ipykernel_launcher.py:2: FutureWarning: read_table is deprecated, use read_csv instead, passing sep='\t'.
  


[[10  1]
 [ 3 11]]
              precision    recall  f1-score   support

           0       0.77      0.91      0.83        11
           1       0.92      0.79      0.85        14

   micro avg       0.84      0.84      0.84        25
   macro avg       0.84      0.85      0.84        25
weighted avg       0.85      0.84      0.84        25

84.0
[[10  1]
 [ 4 10]]
              precision    recall  f1-score   support

           0       0.71      0.91      0.80        11
           1       0.91      0.71      0.80        14

   micro avg       0.80      0.80      0.80        25
   macro avg       0.81      0.81      0.80        25
weighted avg       0.82      0.80      0.80        25

80.0


In [5]:
robot2()

/home/vatsal/.local/lib/python3.6/site-packages/ipykernel_launcher.py:2: FutureWarning: read_table is deprecated, use read_csv instead, passing sep='\t'.
  


[[9 4]
 [4 8]]
              precision    recall  f1-score   support

           0       0.69      0.69      0.69        13
           1       0.67      0.67      0.67        12

   micro avg       0.68      0.68      0.68        25
   macro avg       0.68      0.68      0.68        25
weighted avg       0.68      0.68      0.68        25

68.0
[[11  2]
 [ 1 11]]
              precision    recall  f1-score   support

           0       0.92      0.85      0.88        13
           1       0.85      0.92      0.88        12

   micro avg       0.88      0.88      0.88        25
   macro avg       0.88      0.88      0.88        25
weighted avg       0.88      0.88      0.88        25

88.0


In [6]:
df=pd.read_csv("Iris/Iris.csv",names=['sepal length','sepal width','petal length','petal width','class'])
k = 5

In [7]:
X = df.drop(['class'],axis=1)
Y = df['class']
X_train, X_test, Y_train, Y_test = train_test_split(X,Y,test_size = 0.2)

In [8]:
def euclidean_distance(x, y):   
    ans = np.sqrt(np.sum((x - y) ** 2))
    return ans

In [9]:
Y_train = list(Y_train)
pred = []
for index,row in X_test.iterrows():
    dist= []
    for index1,row1 in X_train.iterrows():
        dist.append(euclidean_distance(row,row1))
        
    our = pd.DataFrame(
    {'a': dist,
     'b': Y_train
    })
    our = our.sort_values(by=['a'])
    sentosa = 0
    virginica = 0
    versicolor = 0
    i = 0
    for index,row in our.iterrows():
        if i >= k:
            break
        if row['b'] == "Iris-setosa":
            sentosa = sentosa + 1 
        elif row['b'] == "Iris-virginica":
            virginica = virginica + 1 
        elif row['b'] == "Iris-versicolor":
            versicolor = versicolor + 1 
        i = i + 1
    if sentosa >= virginica and sentosa >= versicolor:
        pred.append("Iris-setosa")
    elif virginica >= sentosa and virginica >= versicolor:
        pred.append("Iris-virginica")
    elif versicolor >= sentosa and versicolor >= virginica:
        pred.append("Iris-versicolor")

In [10]:
print(confusion_matrix(Y_test,pred))
print(classification_report(Y_test,pred))
print(accuracy_score(Y_test, pred)*100)

[[10  0  0]
 [ 0  8  1]
 [ 0  0  8]]
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        10
Iris-versicolor       1.00      0.89      0.94         9
 Iris-virginica       0.89      1.00      0.94         8

      micro avg       0.96      0.96      0.96        27
      macro avg       0.96      0.96      0.96        27
   weighted avg       0.97      0.96      0.96        27

96.29629629629629


In [11]:
neigh = KNeighborsClassifier()
neigh.fit(X_train, Y_train) 
y_pred = neigh.predict(X_test)
print(confusion_matrix(Y_test,y_pred))
print(classification_report(Y_test,y_pred))
print(accuracy_score(Y_test, y_pred)*100)

[[10  0  0]
 [ 0  8  1]
 [ 0  0  8]]
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        10
Iris-versicolor       1.00      0.89      0.94         9
 Iris-virginica       0.89      1.00      0.94         8

      micro avg       0.96      0.96      0.96        27
      macro avg       0.96      0.96      0.96        27
   weighted avg       0.97      0.96      0.96        27

96.29629629629629
