In [213]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split 
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import r2_score,confusion_matrix,classification_report,accuracy_score
from sklearn.preprocessing import StandardScaler

In [214]:
df=pd.read_csv("wine-quality/data.csv")
learning_rate = 0.01
iterations = 1000
threshold = 0.5
columns = df.columns
columns

Index(['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar',
       'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density',
       'pH', 'sulphates', 'alcohol', 'quality'],
      dtype='object')

In [215]:
X = df.iloc[:,0:12].values
# print(X)
FX = []
a=0
for i in X:
#     print(i)
    if X[a][len(i)-1]==0 or X[a][len(i)-1]==1 or X[a][len(i)-1]==2 or X[a][len(i)-1]==10:
        pass
    else:    
        FX.append(i)
    a=a+1
# FX
df = pd.DataFrame(FX, columns=columns)
# df

In [216]:
X = df.drop(['quality'],axis=1)
Y = df['quality']

# print(len(df[df['quality']==3]))

In [217]:
X_train, X_test, Y_train, Y_test = train_test_split(X,Y,test_size = 0.2)

In [218]:
X_train = (X_train - X_train.mean())/X_train.std()
X_test = (X_test - X_test.mean())/X_test.std()

In [219]:
X_train = pd.concat([X_train,Y_train],axis=1)
ones = np.ones([X_train.shape[0],1])
Y_train = X_train.iloc[:,11:12].values
X_train = X_train.iloc[:,0:11]
X_train = np.concatenate((ones,X_train),axis=1)

In [220]:
Y_train.shape

(3526, 1)

In [221]:
theta = np.zeros([21,12])
theta.shape

(21, 12)

In [222]:
def sigmoid(z):
    return 1 / (1 + np.exp(-z))

In [223]:
def gradient_decent(X_train,Y_train,theta1,learning_rate,iterations):
    
    for i in range(iterations):
        h = sigmoid(np.dot(X_train,theta1.T))
        theta1 = theta1 - (learning_rate/len(X_train)) * np.sum(X_train * (h - Y_train), axis=0)
    
    return theta1

In [224]:
x=0
for i in range(3,9):
    for j in range(i+1,10):
        theta1 = np.zeros([1,12])
        
        Xcopy = []
        Ycopy = []
        W = np.array(Y_train)
        
        for k in range(len(W)):
            if W[k] == j or W[k]==i:
                Xcopy.append(X_train[k])
                Ycopy.append(Y_train[k])
        
        Xcopy = np.array(Xcopy)
        Ycopy = np.array(Ycopy)
#         print(Xcopy.shape)
#         print(Ycopy.shape)
#         print(x)
        theta[x]=gradient_decent(Xcopy,Ycopy,theta1,learning_rate,iterations)
        x = x + 1

In [225]:
# theta

In [226]:
y_pred = []
for index,rows in X_test.iterrows():

    rows = list(rows)
    counts = [0]*7
    c = 0
    for a in range(3,9):
        for b in range(a+1,10):
            y = 0
            for i in range(len(rows)):
                y = y + rows[i]*theta[c][i+1]
            y = y + theta[c][0]
            y = sigmoid(y)
            c = c + 1
            if y >= threshold:
                counts[b-3] = counts[b-3] + 1
            else:
                counts[a-3] = counts[a-3] + 1
#     print(counts)
    y_pred.append(counts.index(max(counts)))
# y_pred
# counts

In [227]:
print((y_pred == Y_test).mean()*100)
print(confusion_matrix(Y_test,y_pred))
# print(classification_report(Y_test,y_pred))
print(accuracy_score(Y_test, y_pred)*100)

24.489795918367346
[[  0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   1   0   0   0   0]
 [  0   1   3   6   7   9   0   0   0]
 [ 10  25  16  96  68  59   0   0   0]
 [ 12  24   7  61 148 142   0   0   0]
 [  2   5   0  19  69  60   0   0   0]
 [  0   4   0   3  14   9   0   0   0]
 [  0   0   0   0   0   2   0   0   0]]
24.489795918367346
