In [136]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split 
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import r2_score,confusion_matrix,classification_report,accuracy_score
from sklearn.preprocessing import StandardScaler

In [137]:
df=pd.read_csv("wine-quality/data.csv")
learning_rate = 0.01
iterations = 1000
# df
columns = df.columns
columns

Index(['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar',
       'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density',
       'pH', 'sulphates', 'alcohol', 'quality'],
      dtype='object')

In [138]:
# X = df.iloc[:,0:12].values
# # print(X)
# FX = []
# a=0
# for i in X:
# #     print(i)
#     if X[a][len(i)-1]==4 or X[a][len(i)-1]==5 or X[a][len(i)-1]==6 or X[a][len(i)-1]==7 or X[a][len(i)-1]==8:
#         FX.append(i)
#     a=a+1
# # FX
# df = pd.DataFrame(FX, columns=columns)
# # df

In [139]:
X = df.drop(['quality'],axis=1)
Y = df['quality']

# print(len(df[df['quality']==9]))

In [140]:
X_train, X_test, Y_train, Y_test = train_test_split(X,Y,test_size = 0.2)

In [141]:
X_train = (X_train - X_train.mean())/X_train.std()
X_test = (X_test - X_test.mean())/X_test.std()

In [142]:
lr = LogisticRegression(solver='lbfgs',multi_class='multinomial',max_iter=iterations)
lr.fit(X_train, Y_train) 
y_pred = lr.predict(X_test)
score = lr.score(X_test,Y_test)
print(score)
print((Y_test == y_pred).mean())
print(confusion_matrix(Y_test,y_pred))
# print(classification_report(Y_test,y_pred))
print(accuracy_score(Y_test, y_pred)*100)

0.5544217687074829
0.5544217687074829
[[  0   0   1   3   0   0]
 [  0   4  15  11   0   0]
 [  0   1 145 109   1   0]
 [  0   0  81 315  19   0]
 [  0   0   6 119  25   0]
 [  0   0   0  14  13   0]]
55.44217687074829


In [143]:
X_train = pd.concat([X_train,Y_train],axis=1)
ones = np.ones([X_train.shape[0],1])
Y_train = X_train.iloc[:,11:12].values
X_train = X_train.iloc[:,0:11]
X_train = np.concatenate((ones,X_train),axis=1)

In [144]:
Y_train.shape

(3526, 1)

In [145]:
theta = np.zeros([11,12])
theta.shape

(11, 12)

In [146]:
def sigmoid(z):
    return 1 / (1 + np.exp(-z))

In [147]:
def gradient_decent(X_train,Y_train,theta1,learning_rate,iterations):
    
    for i in range(iterations):
        h = sigmoid(np.dot(X_train,theta1.T))
        theta1 = theta1 - (learning_rate/len(X_train)) * np.sum(X_train * (h - Y_train), axis=0)
    
    return theta1

In [148]:
for i in range(0,11):
    theta1 = np.zeros([1,12])
    W = np.array(Y_train)
    for j in range(len(W)):
        if W[j] == i:
            W[j] = 1
        else:
            W[j] = 0
    
    theta[i]=gradient_decent(X_train,W,theta1,learning_rate,iterations)

In [149]:
# theta

In [150]:
y_pred = []
for index,rows in X_test.iterrows():

    rows = list(rows)
    max_h=0
    for a in range(0,11):
        y = 0
        for i in range(len(rows)):
            y = y + rows[i]*theta[a][i+1]
        y = y + theta[a][0]
        y = sigmoid(y)
        if y >= max_h:
            label = a
            max_h = y
    y_pred.append(label)
# y_pred

In [151]:
print((y_pred == Y_test).mean()*100)
print(confusion_matrix(Y_test,y_pred))
# print(classification_report(Y_test,y_pred))
print(accuracy_score(Y_test, y_pred)*100)

53.28798185941043
[[  0   0   0   4   0   0]
 [  0   0  18  12   0   0]
 [  0   0 144 112   0   0]
 [  0   0  90 319   6   0]
 [  0   0   7 136   7   0]
 [  0   0   0  26   1   0]]
53.28798185941043
